# Generated by Django 4.2.3 on 2023-07-16 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import painless.models.validator.picture


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, help_text='access to all post by category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.postcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(height_field='pic_height_field', max_length=110, upload_to='blog/post', validators=[painless.models.validator.picture.DimensionValidator(800, 600), django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'jpg', 'jpeg'])], verbose_name='Picture', width_field='pic_width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='access to all posts by tags', null=True, related_name='posts', to='blog.posttag', verbose_name='Tags'),
        ),
    ]
