# Generated by Django 4.2.3 on 2023-07-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category_alter_post_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='sluggggg', max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='sluggggg', max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='sluggggg', max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='sluggggg', max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='sluggggg', max_length=110, unique=True, verbose_name='Slug'),
        ),
    ]
