# Generated by Django 4.2.3 on 2023-07-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_slug_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='sluggggg', max_length=110, unique=True, verbose_name='Slug'),
        ),
    ]
